language: node_js
node_js:
- '7'
- '6'
deploy:
  provider: npm
  api_key: b2pIAo5zvu0QwBCCV1y4Harb0oJixTpJsSpRuvz69LP2v1XUaLKON3k6WrgVznEcyxrlM+aQLit4Y2QXGf/H2bJkU7aa/wqhCqfJTG4voMR2AaCPGaeScHuAzIjfTxLJT/WhLMGhTPB078UboA9MsZ73j9z1o6CtNRHO89ojbfxnB7wWucOwSmEtuH+I0EAmBH/QOFvD7YrW8Ksdbt6/CLoauobRMKYBTA0hdEk6dcjVrGOllgDqlM1VGMyJWz+E1zgaw2/Rhb+ESUjTWserwyqWNkw/RQNlc0l5qPqvCScy+v+UyKzquRDE1I/dnHvlt4DtbYpb0fMmp+bkc02En9mQwEoT29ew1dKeTyzCxNADkySy/dk1eI0M4dnMATJF6KPqNRhKLV3LyBB81uAHBVxNrHM87XSUYaN11TsjdJV/XYnlZboU31HXhPgBkbP30Mr0PsYnRTJJb/0UVtXZLtRlitvlHfBlvESPBWeWsvgOYOFqfD2eHCToBY8V3Du0+qvB3aGSsY46kB/V9wN10YKlUgHDCDtKEODx5SB7ve1MG3o29+a5w6ppE7bvtNWstUhlT0BhW+KTX4BvemQWR5/nKa2eQ0u4s7LIEUK55d8I85EbtFkIcBTpbekbwk9Ppzm6ToiUcdRMM4TgRVysXNNyLyb5wmTBa5AosGDHg2k=
  email: EMAIL
	on:
    branch: master
env:
  global:
    EMAIL: ZPnX3H2pQJ/QpYLVBEcBkDYnFSavXJCZFrwW9km0PueLzUS6bKV2SJjOlkfu9FtueDXmxJtaAnbAyYkNKQvKIO527MaLbN32lrhpyWRT0vAUd03TrLaasD4kRjNcR/R6SqLkeie/XM8FpX3ap/gIWTlwX0yIANpFjeUnrE95Y0SDA66sYN/RR9tJ3R7UCS2tXsOod5VTRUp45svBzu5uiF+5li8bV3nurSOX5aAHQnYK2O6ORc7rvNi7a0/8nWj3z8Ut4D5z/ikTEBHoJb5HH2YZKrkQMTSZ+t60GgxovFRkoeFHwS6Fej9y3lddxeb7u87yIY3zvd9MSiz3XZBjVxoP3gbWg1bHe2vS3+ELxdTqRkbCwUkJahCVxaDylKAKKiWjf0xzBgFdyQUZrvJBT5SPCBgShi4q8OBCFK7Yu/95sVqMOKqwN+se6ABKrrXRoDDh1bqTsifdQqu0JRhMuYaQYVBCkqw1oKyCJBCtvMpeIPDaQpGTO268x80E7x0H8vXJGq7kKk/WcGMsPPC7i/b2AIU4VvDz8hpYsYO7HnkJRKt8x70KI1Gl+jslFG7hvm6JGebKXpOlQ+OpvgeAnXxsg+9IrQsVfPCqp47oLs8A5Xwa7MSOCEap/OWEFVvaw6l8rORpdgRngE1qrjyvT1eJixB4RmeEGErBgVSUxyA=
